### ISSUE TITLE
Log the settings dump on debug 3

### ISSUE THREAD

**Issue by andyneff** [VisionSystemsInc/terra#5]
The settings should be dumped to the log file on debug3

```python
logger.debug3(TerraJSONEncoder.serializableSettings(settings))
```

The question is where in terra should this be slipped in, on logger initialization? It would be easy to slip it into `_SetupTerraLogger.configure_logger`

@drewgilliam

**Comment by drewgilliam** [comment]
Note you do appear to log settings in `_SetupTerraLogger.configure_logger`, but only to the file handler:

https://github.com/VisionSystemsInc/terra/blob/31694d83726e0e8162f5acf217d09787aa3fe80b/terra/logger.py#L260-L267

**Comment by andyneff** [comment]
Ah, that makes sense.

A nice compromise would be to, on a per service basis:
1. Have settings track which elements get accessed. That should be easy enough, just has to be recursive.
2. Have a way to get that list, loop through the list, and print those settings at the end of a service, or on crash
3. Reset the list and start again for the next service

This way, only the settings used are listed, and you don't have to keep the list up to date.

**Comment by andyneff** [comment]
The logger "logs" individual settings files to disk, to take the place of this.
