### ISSUE TITLE
original_zone undefined in task.py

### ISSUE THREAD

**Issue by NoahRJohnson** [VisionSystemsInc/terra#55]
Terra crashed while running CropAndCalibrate tasks. It seems that settings.configured was False before a task ran, and True afterwards, causing this issue. Ran with virtualenv compute on Windows, using the ProcessPoolExecutor.

`Traceback (most recent call last):
  File "C:\Python37\Lib\concurrent\futures\process.py", line 239, in _process_wo
rker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "c:\users\noah\git\terra_dsm\external\terra\terra\task.py", line 140, in
__call__
    settings.terra.zone = original_zone
UnboundLocalError: local variable 'original_zone' referenced before assignment`

**Comment by andyneff** [comment]
This issue has been "solved", but I want to investigate it a little before closing it.

I think the serializer for settings doesn't set the configured flag on right, and that's bad

**Comment by andyneff** [comment]
Fixed in #88
